apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bossraid-attacks
  namespace: kafka
  labels:
    strimzi.io/cluster: bossraid
spec:
  partitions: 24
  replicas: 1
  config:
    retention.ms: 86400000
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bossraid-score-updates
  namespace: kafka
  labels:
    strimzi.io/cluster: bossraid
spec:
  partitions: 24
  replicas: 1
  config:
    retention.ms: 86400000
    cleanup.policy: delete
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: bossraid-integrity
  namespace: kafka
  labels:
    strimzi.io/cluster: bossraid
spec:
  partitions: 24
  replicas: 1
  config:
    retention.ms: 86400000
    cleanup.policy: delete
