apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bossraid-dashboard
  namespace: demo
spec:
  ingressClassName: __INGRESS_CLASS__
  tls:
  - hosts:
    - __HOST__
    secretName: __TLS_SECRET__
  rules:
  - host: __HOST__
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bossraid-dashboard
            port:
              number: 8080
